apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn }}
