namespace: cloudmart-staging

replicaCount: 1

image:
  repository: 143629080002.dkr.ecr.us-east-1.amazonaws.com/staging/cloudmart/frontend
  tag: latest

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

ingress:
  certificateArn: "arn:aws:acm:us-east-1:143629080002:certificate/staging-cert"
  wafAclArn: "arn:aws:wafv2:us-east-1:143629080002:regional/webacl/cloudmart-waf-staging/id"
