namespace: cloudmart-staging

replicaCount: 1

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/cloudmart/frontend
  tag: latest

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

ingress:
  certificateArn: "arn:aws:acm:us-east-1:<AWS_ACCOUNT_ID>:certificate/staging-cert"
  wafAclArn: "arn:aws:wafv2:us-east-1:<AWS_ACCOUNT_ID>:regional/webacl/cloudmart-waf-staging/id"
