namespace: cloudmart-prod

image:
  repository: 143629080002.dkr.ecr.us-east-1.amazonaws.com/prod/cloudmart/frontend
  tag: latest

replicaCount: 2

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  certificateArn: "arn:aws:acm:us-east-1:143629080002:certificate/prod-cert"
  wafAclArn: "arn:aws:wafv2:us-east-1:143629080002:regional/webacl/cloudmart-waf/id"
