apiVersion: v1
kind: Secret
metadata:
  name: user-service-db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: "CloudMartAdmin123!"
  DB_HOST: "cloudmart-postgres-staging.cm30s6swwvvj.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "cloudmart_user"
  DB_NAME: "cloudmart"
