apiVersion: v1
kind: Secret
metadata:
  name: user-service-db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: "CloudMartAdmin123!" # In a real scenario, this would be a Helm --set or ExternalSecret
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  DATABASE_URL: "postgresql://{{ .Values.config.dbUser }}:CloudMartAdmin123!@{{ .Values.config.dbHost }}:{{ .Values.config.dbPort }}/{{ .Values.config.dbName }}"
