namespace: cloudmart-prod

replicaCount: 2

image:
  tag: latest

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  dynamodbTableName: cloudmart-products
  awsRegion: us-east-1
  storeBackend: dynamodb

seed:
  enabled: false

serviceAccount:
  irsaRoleArn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/cloudmart-product-service-role-prod"

rollout:
  enabled: false
