{{- if not .Values.rollout.enabled -}}
apiVersion: apps/v1
kind: Deployment
...
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
{{- end -}}
