{{- if .Values.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: product-service-seed
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: product-service-seed
    spec:
      restartPolicy: Never
      serviceAccountName: product-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: seed-products
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "seed_dynamodb.py"]
          env:
            - name: DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: dynamodbTableName
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: awsRegion
{{- end }}
