namespace: cloudmart-staging

replicaCount: 1

image:
  tag: latest

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

config:
  sqsQueueUrl: "https://sqs.us-east-1.amazonaws.com/<AWS_ACCOUNT_ID>/cloudmart-orders-staging"
  awsRegion: us-east-1

serviceAccount:
  irsaRoleArn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/cloudmart-notification-service-role-staging"
