image:
  repository: 143629080002.dkr.ecr.us-east-1.amazonaws.com/cloudmart-staging/notification-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  sqsQueueUrl: "" # Set in values-prod.yaml
  awsRegion: us-east-1
  queueBackend: sqs
  emailBackend: ses
  fromEmail: "admin@cloudmart.example"

serviceAccount:
  irsaRoleArn: ""   # Override in values-prod.yaml

namespace: cloudmart-prod
