namespace: cloudmart-prod

replicaCount: 2

image:
  repository: 143629080002.dkr.ecr.us-east-1.amazonaws.com/prod/cloudmart/order-service
  tag: latest

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  sqsQueueUrl: "https://sqs.us-east-1.amazonaws.com/143629080002/cloudmart-orders-prod"
  awsRegion: us-east-1

serviceAccount:
  irsaRoleArn: "arn:aws:iam::143629080002:role/cloudmart-order-service-role-prod"
