image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/cloudmart-staging/order-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8002

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

config:
  sqsQueueUrl: "" # Set in values-prod.yaml
  awsRegion: us-east-1

serviceAccount:
  irsaRoleArn: ""   # Override in values-prod.yaml

namespace: cloudmart-prod
