namespace: cloudmart-staging

replicaCount: 1

image:
  tag: latest

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

config:
  awsRegion: us-east-1
  rdsSecretName: cloudmart/staging/rds/user-service

serviceAccount:
  irsaRoleArn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/cloudmart-user-service-role-staging"
